### ISSUE TITLE
Refactor pawnfirstmove

### ISSUE THREAD

**Issue by ngjunsiang** [YMlvg/ChessGame#16]
chess.py [line 429](https://github.com/YMlvg/ChessGame/blob/6ed265130e75367d203409c876b05ed353f1bcae/chess.py#L429) to [line 465](https://github.com/YMlvg/ChessGame/blob/6ed265130e75367d203409c876b05ed353f1bcae/chess.py#L465)

## Issue

- Difficult to understand the code, as it uses two classes with unclear interaction between them
- Illegal modification of `__class__` dunder attribute. This obscures the class properties which make it harder to debug.
- Duplication of code makes it more likely to introduce bugs during debugging

## Suggested resolution

Consider refactoring code to use an attribute (eg. `moved`) to determine if the piece has been moved from its starting position

**Comment by SaltiestWonton** [comment]
done
